name: Skylands
version: 1.0
author: michaelkrauty
main: me.michaelkrauty.Skylands.Main
commands:
  sudosay:
    permission: sudo.say
    usage: /sudosay <player> <message>
  staffadd:
    permission: server.admin
    usage: /staffadd <player>
  donatoradd:
    permission: server.admin
    usage: /donatoradd <player>
  staffremove:
    permission: server.admin
    usage: /staffremove <player>
  donatorremove:
    permission: server.admin
    usage: /donatorremove <player>
  callhacks:
    permission: hacks.call
    usage: /callhacks <player>
  cc:
    usage: /cc
  staff:
    usage: /staff <text>
  staffasks:
    usage: /staffasks <player>
  staffasks-reset:
    usage: /staffasks-reset <player>
    permission: staff.asks.reset
  staff-add:
    usage: /staff-add <text> <text>
  staff-remove:
    usage: /staff-remove <text> <text>
  effectsudo:
    usage: /effectsudo <player> <text>
    permission: effects.console
  effects:
    usage: /effects <text> <text>
    permission: effects.*